### ISSUE TITLE
Acquisition frequency mismatch 

### ISSUE THREAD

**Issue by frikyng** [apacker83/PackIO#2]
Hi Adam, 

I just saw that the data I acquired in PackIO with 30 kHz were actually sampled at 30030 Hz. Since I wanted to match this data to a neuropixel recording this created some issues. I could resolve the mismatch by downsampling the PackIO data to 30000 Hz, but this still left some small mismatch in my data - probably the number precision in framework of the computer was not accurate enough for a perfect downsampling. Therefore, do you know how to resolve this issue? 
I have checked that PackIo was actually configured to 30 kHz and I have checked older recordings that were done a year ago that also contain this issue, so I think the mismatch in frequencies is caused by the program. 

Best, 
Friedrich

**Comment by apacker83** [comment]
Hi Friedrich,

This is intriguing, and confusing. Could you let me know what NI-DAQ hardware you used for the recording?  And could you share with me a file you acquired that had this problem please?

Thank you,
Adam

**Comment by frikyng** [comment]
Hi, 
here is a short file with the 30030 Hz acquisition frequency. I have also uploaded the Matlab function I use to load the data. 
[https://github.com/frikyng/paq_data.git](url)
Regarding the hardware, I am using the NI USB 6221 I/O device. 

Friedrich

**Comment by apacker83** [comment]
The NI USB 6221 device has a fundamental "timing resolution" of 50 ns.  Therefore, only certain acquisition frequencies are allowed.  Apparently 30000 Hz is not allowed with this specific device, but increments of 45 Hz around 30030 Hz such as 29985 Hz and 30075 Hz are allowed given the timing resolution.  Thanks for your help, which helped uncover the source of the confusion!

Here is a definition of timing resolution from the NI website:
Sample and update rates for analog input and output tasks are restricted to discrete values when using an onboard timing engine. The difference in clock periods between two adjacent rates is known as timing resolution. NI-DAQmx will coerce a selected frequency up to the next available frequency if it cannot generate the exact one specified by the user.

Example
The NI PXIe-6363 has a specified timing resolution of 10 ns. This means that it can generate or acquire data at integer multiples of 10 ns. For example, 32,000.00 Hz and 32,010.2432... Hz are two adjacent frequencies, as their clock periods are 31.250 µs & 31.240 µs, respectively. To find the next available frequency, add or subtract the timing resolution to a known clock period.

Source: https://www.ni.com/en-gb/support/documentation/supplemental/16/specifications-explained--ni-multifunction-i-o--mio--daq.html

**Comment by frikyng** [comment]
Hi Adam, 
thanks for clearing this up. I'll find a workaround for the mismatch then. 

Friedrich
